spring:
  application:
    name: geofence
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:geofence
    driver-class-name: org.h2.Driver
    username: geofence
    password: 1q2w3e4r!!
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    cache: false


